# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartoGraph
                                 A QGIS plugin
 This plugin creates graphs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-16
        copyright            : (C) 2024 by Jilin University
        email                : 1970329479@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CartoGraph class from file CartoGraph.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CartoGrapher import CartoGraph
    from .qgisUitils.LayerUtils import  readRasterFile, addMapLayer, readVectorFile
    from .qgisUitils.qgisMenu import menuProvider
    from .qgisUitils.layerPropWindowWidgter import LayerPropWindowWidgeter
    # from mainWindow import  MainWindow.
    return CartoGraph(iface)
