# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CartoGrapher_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.gui import QgsDockWidget
# from mainWindow import MainWindow

class Ui_CartoGraphDialogBase(object):
    def setupUi(self, CartoGraphDialogBase):
        CartoGraphDialogBase.setObjectName("CartoGraphDialogBase")
        CartoGraphDialogBase.resize(905, 627)
        self.frame = QtWidgets.QFrame(CartoGraphDialogBase)
        self.frame.setGeometry(QtCore.QRect(300, 0, 601, 631))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.mDockWidget = QgsDockWidget(CartoGraphDialogBase)
        self.mDockWidget.setGeometry(QtCore.QRect(0, 0, 300, 621))
        self.mDockWidget.setObjectName("mDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(140, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.mDockWidget.setWidget(self.dockWidgetContents)


        self.retranslateUi(CartoGraphDialogBase)
        QtCore.QMetaObject.connectSlotsByName(CartoGraphDialogBase)

    def retranslateUi(self, CartoGraphDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CartoGraphDialogBase.setWindowTitle(_translate("CartoGraphDialogBase", "CartoGrapher"))
        self.pushButton.setText(_translate("CartoGraphDialogBase", "PushButton"))

