# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartolinegen_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CartoLineGenDialogBase(object):
    def setupUi(self, CartoLineGenDialogBase):
        CartoLineGenDialogBase.setObjectName("CartoLineGenDialogBase")
        CartoLineGenDialogBase.resize(442, 451)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CartoLineGenDialogBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(CartoLineGenDialogBase)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cb_all = QtWidgets.QCheckBox(CartoLineGenDialogBase)
        self.cb_all.setObjectName("cb_all")
        self.verticalLayout_2.addWidget(self.cb_all)
        self.dlg_layer = QtWidgets.QComboBox(CartoLineGenDialogBase)
        self.dlg_layer.setObjectName("dlg_layer")
        self.verticalLayout_2.addWidget(self.dlg_layer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dlg_selected = QtWidgets.QCheckBox(CartoLineGenDialogBase)
        self.dlg_selected.setObjectName("dlg_selected")
        self.horizontalLayout.addWidget(self.dlg_selected)
        self.dlg_remove_small = QtWidgets.QCheckBox(CartoLineGenDialogBase)
        self.dlg_remove_small.setChecked(True)
        self.dlg_remove_small.setObjectName("dlg_remove_small")
        self.horizontalLayout.addWidget(self.dlg_remove_small)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(CartoLineGenDialogBase)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dlg_scale = QtWidgets.QLineEdit(CartoLineGenDialogBase)
        self.dlg_scale.setObjectName("dlg_scale")
        self.horizontalLayout_2.addWidget(self.dlg_scale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(CartoLineGenDialogBase)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dlg_type = QtWidgets.QComboBox(CartoLineGenDialogBase)
        self.dlg_type.setObjectName("dlg_type")
        self.dlg_type.addItem("")
        self.dlg_type.addItem("")
        self.dlg_type.addItem("")
        self.dlg_type.addItem("")
        self.horizontalLayout_3.addWidget(self.dlg_type)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(CartoLineGenDialogBase)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.dlg_file = QgsFileWidget(CartoLineGenDialogBase)
        self.dlg_file.setObjectName("dlg_file")
        self.verticalLayout_2.addWidget(self.dlg_file)
        self.dlg_add = QtWidgets.QCheckBox(CartoLineGenDialogBase)
        self.dlg_add.setEnabled(True)
        self.dlg_add.setChecked(True)
        self.dlg_add.setObjectName("dlg_add")
        self.verticalLayout_2.addWidget(self.dlg_add)
        self.dlg_warning = QtWidgets.QLabel(CartoLineGenDialogBase)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dlg_warning.setFont(font)
        self.dlg_warning.setText("")
        self.dlg_warning.setObjectName("dlg_warning")
        self.verticalLayout_2.addWidget(self.dlg_warning)
        self.button_box = QtWidgets.QDialogButtonBox(CartoLineGenDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box)

        self.retranslateUi(CartoLineGenDialogBase)
        self.button_box.accepted.connect(CartoLineGenDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(CartoLineGenDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CartoLineGenDialogBase)

    def retranslateUi(self, CartoLineGenDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CartoLineGenDialogBase.setWindowTitle(_translate("CartoLineGenDialogBase", "Cartographic Line Generalisation - CartoLineGen"))
        self.label.setText(_translate("CartoLineGenDialogBase", "Input line or polygon layer to generalise:"))
        self.cb_all.setText(_translate("CartoLineGenDialogBase", "Generalize all suitable layers"))
        self.dlg_selected.setText(_translate("CartoLineGenDialogBase", "Use only selected features"))
        self.dlg_remove_small.setText(_translate("CartoLineGenDialogBase", "Remove too small areas"))
        self.label_2.setText(_translate("CartoLineGenDialogBase", "Map scale denominator:"))
        self.label_4.setText(_translate("CartoLineGenDialogBase", "Generalisation type:"))
        self.dlg_type.setItemText(0, _translate("CartoLineGenDialogBase", "Simplification + Smoothing"))
        self.dlg_type.setItemText(1, _translate("CartoLineGenDialogBase", "Simplification"))
        self.dlg_type.setItemText(2, _translate("CartoLineGenDialogBase", "Smoothing"))
        self.dlg_type.setItemText(3, _translate("CartoLineGenDialogBase", "Orthogonal Segments"))
        self.label_3.setText(_translate("CartoLineGenDialogBase", "Specify output file:"))
        self.dlg_add.setText(_translate("CartoLineGenDialogBase", "Add result to canvas"))
from qgsfilewidget import QgsFileWidget
