# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExaggerateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExaggerateDialog(object):
    def setupUi(self, ExaggerateDialog):
        ExaggerateDialog.setObjectName("ExaggerateDialog")
        ExaggerateDialog.resize(446, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/CartoGrapher/resources/m.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExaggerateDialog.setWindowIcon(icon)
        self.layerCbmBox = QgsMapLayerComboBox(ExaggerateDialog)
        self.layerCbmBox.setGeometry(QtCore.QRect(10, 50, 160, 27))
        self.layerCbmBox.setObjectName("layerCbmBox")
        self.label_5 = QtWidgets.QLabel(ExaggerateDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_5.setObjectName("label_5")
        self.output_checkBox_2 = QtWidgets.QCheckBox(ExaggerateDialog)
        self.output_checkBox_2.setGeometry(QtCore.QRect(10, 250, 351, 19))
        self.output_checkBox_2.setChecked(True)
        self.output_checkBox_2.setObjectName("output_checkBox_2")
        self.output_file = QgsFileWidget(ExaggerateDialog)
        self.output_file.setGeometry(QtCore.QRect(10, 200, 321, 27))
        self.output_file.setObjectName("output_file")
        self.label_7 = QtWidgets.QLabel(ExaggerateDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(ExaggerateDialog)
        self.label.setGeometry(QtCore.QRect(10, 100, 191, 16))
        self.label.setObjectName("label")
        self.edit_scale = QtWidgets.QLineEdit(ExaggerateDialog)
        self.edit_scale.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.edit_scale.setObjectName("edit_scale")
        self.closeBtn = QtWidgets.QPushButton(ExaggerateDialog)
        self.closeBtn.setGeometry(QtCore.QRect(220, 300, 93, 28))
        self.closeBtn.setAutoDefault(False)
        self.closeBtn.setObjectName("closeBtn")
        self.runBtn = QtWidgets.QPushButton(ExaggerateDialog)
        self.runBtn.setGeometry(QtCore.QRect(100, 300, 93, 28))
        self.runBtn.setDefault(True)
        self.runBtn.setObjectName("runBtn")

        self.retranslateUi(ExaggerateDialog)
        QtCore.QMetaObject.connectSlotsByName(ExaggerateDialog)

    def retranslateUi(self, ExaggerateDialog):
        _translate = QtCore.QCoreApplication.translate
        ExaggerateDialog.setWindowTitle(_translate("ExaggerateDialog", "Exaggerate"))
        self.label_5.setText(_translate("ExaggerateDialog", "Input layer or shp："))
        self.output_checkBox_2.setText(_translate("ExaggerateDialog", "Open output file after running algorithm"))
        self.label_7.setText(_translate("ExaggerateDialog", "Exaggerated layer:"))
        self.label.setText(_translate("ExaggerateDialog", "Exaggeration scale:"))
        self.closeBtn.setText(_translate("ExaggerateDialog", "关闭"))
        self.runBtn.setText(_translate("ExaggerateDialog", "运行"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
# import resources_rc
