# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layerDissolveWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DissolveByAttribute(object):
    def setupUi(self, DissolveByAttribute):
        DissolveByAttribute.setObjectName("DissolveByAttribute")
        DissolveByAttribute.resize(642, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/CartoGrapher/resources/m.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DissolveByAttribute.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(DissolveByAttribute)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 381, 391))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Parameters = QtWidgets.QWidget()
        self.Parameters.setObjectName("Parameters")
        self.label = QtWidgets.QLabel(self.Parameters)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 16))
        self.label.setObjectName("label")
        self.mapLayerComboBox = QgsMapLayerComboBox(self.Parameters)
        self.mapLayerComboBox.setGeometry(QtCore.QRect(20, 40, 201, 27))
        self.mapLayerComboBox.setObjectName("mapLayerComboBox")
        self.select_checkBox = QtWidgets.QCheckBox(self.Parameters)
        self.select_checkBox.setGeometry(QtCore.QRect(20, 80, 211, 31))
        self.select_checkBox.setObjectName("select_checkBox")
        self.label_2 = QtWidgets.QLabel(self.Parameters)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 171, 16))
        self.label_2.setObjectName("label_2")
        self.mFieldComboBox = QgsFieldComboBox(self.Parameters)
        self.mFieldComboBox.setGeometry(QtCore.QRect(20, 150, 201, 27))
        self.mFieldComboBox.setObjectName("mFieldComboBox")
        self.widget = QtWidgets.QWidget(self.Parameters)
        self.widget.setGeometry(QtCore.QRect(20, 210, 301, 41))
        self.widget.setObjectName("widget")
        self.separate_checkBox = QtWidgets.QCheckBox(self.widget)
        self.separate_checkBox.setGeometry(QtCore.QRect(10, 10, 281, 21))
        self.separate_checkBox.setObjectName("separate_checkBox")
        self.label_3 = QtWidgets.QLabel(self.Parameters)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 91, 16))
        self.label_3.setObjectName("label_3")
        self.output_FileWidget = QgsFileWidget(self.Parameters)
        self.output_FileWidget.setGeometry(QtCore.QRect(20, 280, 321, 27))
        self.output_FileWidget.setObjectName("output_FileWidget")
        self.label_4 = QtWidgets.QLabel(self.Parameters)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 191, 16))
        self.label_4.setObjectName("label_4")
        self.output_checkBox = QtWidgets.QCheckBox(self.Parameters)
        self.output_checkBox.setGeometry(QtCore.QRect(20, 320, 351, 19))
        self.output_checkBox.setChecked(True)
        self.output_checkBox.setObjectName("output_checkBox")
        self.tabWidget.addTab(self.Parameters, "")
        self.Log = QtWidgets.QWidget()
        self.Log.setObjectName("Log")
        self.tabWidget.addTab(self.Log, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(DissolveByAttribute)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(380, 0, 251, 391))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.progressBar = QtWidgets.QProgressBar(DissolveByAttribute)
        self.progressBar.setGeometry(QtCore.QRect(20, 410, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.cancelBtn = QtWidgets.QPushButton(DissolveByAttribute)
        self.cancelBtn.setGeometry(QtCore.QRect(500, 410, 93, 28))
        self.cancelBtn.setObjectName("cancelBtn")
        self.runBtn = QtWidgets.QPushButton(DissolveByAttribute)
        self.runBtn.setGeometry(QtCore.QRect(190, 450, 93, 28))
        self.runBtn.setObjectName("runBtn")
        self.closeBtn = QtWidgets.QPushButton(DissolveByAttribute)
        self.closeBtn.setGeometry(QtCore.QRect(310, 450, 93, 28))
        self.closeBtn.setObjectName("closeBtn")

        self.retranslateUi(DissolveByAttribute)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DissolveByAttribute)

    def retranslateUi(self, DissolveByAttribute):
        _translate = QtCore.QCoreApplication.translate
        DissolveByAttribute.setWindowTitle(_translate("DissolveByAttribute", "Dissolve by attribute"))
        self.label.setText(_translate("DissolveByAttribute", "Input layer or shp"))
        self.select_checkBox.setText(_translate("DissolveByAttribute", "Selected features only"))
        self.label_2.setText(_translate("DissolveByAttribute", "Dissolve field(s)"))
        self.separate_checkBox.setText(_translate("DissolveByAttribute", "Keep disjoint features separate"))
        self.label_3.setText(_translate("DissolveByAttribute", "Dissolved"))
        self.label_4.setText(_translate("DissolveByAttribute", "Advanced Parameters"))
        self.output_checkBox.setText(_translate("DissolveByAttribute", "Open output file after running algorithm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Parameters), _translate("DissolveByAttribute", "Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log), _translate("DissolveByAttribute", "Log"))
        self.textEdit.setHtml(_translate("DissolveByAttribute", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Dissolve</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This algorithm takes a vector layer and combines the features(selected or by field) into new features. One or more attributes can be specified to dissolve features</p></body></html>"))
        self.cancelBtn.setText(_translate("DissolveByAttribute", "Cancel"))
        self.runBtn.setText(_translate("DissolveByAttribute", "运行"))
        self.closeBtn.setText(_translate("DissolveByAttribute", "关闭"))
from qgsfieldcombobox import QgsFieldComboBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
# import resources_rc
