# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LayoutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayoutDialog(object):
    def setupUi(self, LayoutDialog):
        LayoutDialog.setObjectName("LayoutDialog")
        LayoutDialog.resize(535, 527)
        self.label_9 = QtWidgets.QLabel(LayoutDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_9.setObjectName("label_9")
        self.mapLayerComboBox_3 = QgsMapLayerComboBox(LayoutDialog)
        self.mapLayerComboBox_3.setGeometry(QtCore.QRect(10, 50, 201, 27))
        self.mapLayerComboBox_3.setObjectName("mapLayerComboBox_3")
        self.checkBox_legend = QtWidgets.QCheckBox(LayoutDialog)
        self.checkBox_legend.setGeometry(QtCore.QRect(10, 100, 211, 31))
        self.checkBox_legend.setChecked(True)
        self.checkBox_legend.setObjectName("checkBox_legend")
        self.checkBox_scalebar = QtWidgets.QCheckBox(LayoutDialog)
        self.checkBox_scalebar.setGeometry(QtCore.QRect(180, 100, 211, 31))
        self.checkBox_scalebar.setChecked(True)
        self.checkBox_scalebar.setObjectName("checkBox_scalebar")
        self.checkBox_arrow = QtWidgets.QCheckBox(LayoutDialog)
        self.checkBox_arrow.setGeometry(QtCore.QRect(350, 100, 211, 31))
        self.checkBox_arrow.setChecked(True)
        self.checkBox_arrow.setObjectName("checkBox_arrow")
        self.output_FileWidget_3 = QgsFileWidget(LayoutDialog)
        self.output_FileWidget_3.setGeometry(QtCore.QRect(10, 420, 321, 27))
        self.output_FileWidget_3.setObjectName("output_FileWidget_3")
        self.label_11 = QtWidgets.QLabel(LayoutDialog)
        self.label_11.setGeometry(QtCore.QRect(10, 400, 281, 16))
        self.label_11.setObjectName("label_11")
        self.closeBtn = QtWidgets.QPushButton(LayoutDialog)
        self.closeBtn.setGeometry(QtCore.QRect(290, 470, 93, 28))
        self.closeBtn.setObjectName("closeBtn")
        self.runBtn = QtWidgets.QPushButton(LayoutDialog)
        self.runBtn.setGeometry(QtCore.QRect(170, 470, 93, 28))
        self.runBtn.setDefault(True)
        self.runBtn.setObjectName("runBtn")
        self.comboBox_grid = QtWidgets.QComboBox(LayoutDialog)
        self.comboBox_grid.setGeometry(QtCore.QRect(140, 160, 291, 22))
        self.comboBox_grid.setObjectName("comboBox_grid")
        self.comboBox_grid.addItem("")
        self.comboBox_grid.addItem("")
        self.comboBox_grid.addItem("")
        self.label_13 = QtWidgets.QLabel(LayoutDialog)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 171, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(LayoutDialog)
        self.label_14.setGeometry(QtCore.QRect(10, 210, 171, 16))
        self.label_14.setObjectName("label_14")
        self.SpinBox_intervals = QgsDoubleSpinBox(LayoutDialog)
        self.SpinBox_intervals.setGeometry(QtCore.QRect(10, 240, 211, 27))
        self.SpinBox_intervals.setDecimals(8)
        self.SpinBox_intervals.setSingleStep(1e-06)
        self.SpinBox_intervals.setObjectName("SpinBox_intervals")
        self.txt_title = QtWidgets.QLineEdit(LayoutDialog)
        self.txt_title.setGeometry(QtCore.QRect(10, 330, 221, 27))
        self.txt_title.setObjectName("txt_title")
        self.label_15 = QtWidgets.QLabel(LayoutDialog)
        self.label_15.setGeometry(QtCore.QRect(10, 300, 171, 16))
        self.label_15.setObjectName("label_15")
        self.mQgsProjectionSelectionWidget = QgsProjectionSelectionWidget(LayoutDialog)
        self.mQgsProjectionSelectionWidget.setGeometry(QtCore.QRect(270, 240, 211, 27))
        self.mQgsProjectionSelectionWidget.setObjectName("mQgsProjectionSelectionWidget")
        self.label_16 = QtWidgets.QLabel(LayoutDialog)
        self.label_16.setGeometry(QtCore.QRect(270, 210, 171, 16))
        self.label_16.setObjectName("label_16")

        self.retranslateUi(LayoutDialog)
        QtCore.QMetaObject.connectSlotsByName(LayoutDialog)

    def retranslateUi(self, LayoutDialog):
        _translate = QtCore.QCoreApplication.translate
        LayoutDialog.setWindowTitle(_translate("LayoutDialog", "Layout Settings"))
        self.label_9.setText(_translate("LayoutDialog", "Connected layer:"))
        self.checkBox_legend.setText(_translate("LayoutDialog", "Adding legends"))
        self.checkBox_scalebar.setText(_translate("LayoutDialog", "Adding Scale bar"))
        self.checkBox_arrow.setText(_translate("LayoutDialog", "Adding North arrow"))
        self.label_11.setText(_translate("LayoutDialog", "Layout path(png format in default):"))
        self.closeBtn.setText(_translate("LayoutDialog", "关闭"))
        self.runBtn.setText(_translate("LayoutDialog", "运行"))
        self.comboBox_grid.setItemText(0, _translate("LayoutDialog", "Solid with exterior annotations"))
        self.comboBox_grid.setItemText(1, _translate("LayoutDialog", "Solid with interior annotations"))
        self.comboBox_grid.setItemText(2, _translate("LayoutDialog", "InteriorExterior annotations"))
        self.label_13.setText(_translate("LayoutDialog", "Grid symbol:"))
        self.label_14.setText(_translate("LayoutDialog", "Grid intervals:"))
        self.label_15.setText(_translate("LayoutDialog", "Layout title:"))
        self.label_16.setText(_translate("LayoutDialog", "Layout crs:"))
from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
