# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimplifyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimplifyWindow(object):
    def setupUi(self, SimplifyWindow):
        SimplifyWindow.setObjectName("SimplifyWindow")
        SimplifyWindow.resize(686, 536)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/CartoGrapher/resources/m.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimplifyWindow.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(SimplifyWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 431, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.Parameters_3 = QtWidgets.QWidget()
        self.Parameters_3.setObjectName("Parameters_3")
        self.label_9 = QtWidgets.QLabel(self.Parameters_3)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 171, 16))
        self.label_9.setObjectName("label_9")
        self.mapLayerComboBox_3 = QgsMapLayerComboBox(self.Parameters_3)
        self.mapLayerComboBox_3.setGeometry(QtCore.QRect(20, 40, 201, 27))
        self.mapLayerComboBox_3.setObjectName("mapLayerComboBox_3")
        self.select_checkBox_3 = QtWidgets.QCheckBox(self.Parameters_3)
        self.select_checkBox_3.setGeometry(QtCore.QRect(20, 80, 211, 31))
        self.select_checkBox_3.setObjectName("select_checkBox_3")
        self.label_10 = QtWidgets.QLabel(self.Parameters_3)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 171, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Parameters_3)
        self.label_11.setGeometry(QtCore.QRect(20, 290, 91, 16))
        self.label_11.setObjectName("label_11")
        self.output_FileWidget_3 = QgsFileWidget(self.Parameters_3)
        self.output_FileWidget_3.setGeometry(QtCore.QRect(20, 310, 321, 27))
        self.output_FileWidget_3.setObjectName("output_FileWidget_3")
        self.output_checkBox_3 = QtWidgets.QCheckBox(self.Parameters_3)
        self.output_checkBox_3.setGeometry(QtCore.QRect(20, 350, 351, 19))
        self.output_checkBox_3.setChecked(True)
        self.output_checkBox_3.setObjectName("output_checkBox_3")
        self.simplifyComboBox = QtWidgets.QComboBox(self.Parameters_3)
        self.simplifyComboBox.setGeometry(QtCore.QRect(20, 230, 271, 22))
        self.simplifyComboBox.setObjectName("simplifyComboBox")
        self.simplifyComboBox.addItem("")
        self.simplifyComboBox.addItem("")
        self.label_12 = QtWidgets.QLabel(self.Parameters_3)
        self.label_12.setGeometry(QtCore.QRect(20, 200, 191, 16))
        self.label_12.setObjectName("label_12")
        self.tolerance_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Parameters_3)
        self.tolerance_doubleSpinBox.setGeometry(QtCore.QRect(20, 160, 271, 22))
        self.tolerance_doubleSpinBox.setDecimals(12)
        self.tolerance_doubleSpinBox.setSingleStep(0.01)
        self.tolerance_doubleSpinBox.setProperty("value", 1.0)
        self.tolerance_doubleSpinBox.setObjectName("tolerance_doubleSpinBox")
        self.tabWidget_3.addTab(self.Parameters_3, "")
        self.Log_3 = QtWidgets.QWidget()
        self.Log_3.setObjectName("Log_3")
        self.tabWidget_3.addTab(self.Log_3, "")
        self.horizontalLayout_5.addWidget(self.tabWidget_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(SimplifyWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(430, 0, 251, 431))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_6.addWidget(self.textEdit_3)
        self.closeBtn = QtWidgets.QPushButton(SimplifyWindow)
        self.closeBtn.setGeometry(QtCore.QRect(360, 490, 93, 28))
        self.closeBtn.setObjectName("closeBtn")
        self.progressBar = QtWidgets.QProgressBar(SimplifyWindow)
        self.progressBar.setGeometry(QtCore.QRect(70, 450, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.runBtn = QtWidgets.QPushButton(SimplifyWindow)
        self.runBtn.setGeometry(QtCore.QRect(240, 490, 93, 28))
        self.runBtn.setDefault(True)
        self.runBtn.setObjectName("runBtn")
        self.cancelBtn = QtWidgets.QPushButton(SimplifyWindow)
        self.cancelBtn.setGeometry(QtCore.QRect(550, 450, 93, 28))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(SimplifyWindow)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimplifyWindow)

    def retranslateUi(self, SimplifyWindow):
        _translate = QtCore.QCoreApplication.translate
        SimplifyWindow.setWindowTitle(_translate("SimplifyWindow", "Simplify Polygons"))
        self.label_9.setText(_translate("SimplifyWindow", "Input layer or shp"))
        self.select_checkBox_3.setText(_translate("SimplifyWindow", "Selected features only"))
        self.label_10.setText(_translate("SimplifyWindow", "Simplify tolerance:"))
        self.label_11.setText(_translate("SimplifyWindow", "Simplified:"))
        self.output_checkBox_3.setText(_translate("SimplifyWindow", "Open output file after running algorithm"))
        self.simplifyComboBox.setItemText(0, _translate("SimplifyWindow", "Douglas-Peucker(Distance)"))
        self.simplifyComboBox.setItemText(1, _translate("SimplifyWindow", "Visvalingam(Area)"))
        self.label_12.setText(_translate("SimplifyWindow", "Simplification method"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Parameters_3), _translate("SimplifyWindow", "Parameters"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Log_3), _translate("SimplifyWindow", "Log"))
        self.textEdit_3.setHtml(_translate("SimplifyWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Simplify  Polygons</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This algorithm simplifies the geometries in a line or polygon layer.It creates a new layer with less number of vertices.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Two simplification methods are provied:  Distance based(Douglas-Peucker) and area based(Visvalingam).</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The tolerance parameter indicates the threshold that based on the map unit to decide whether two nodes will be removed(if distance is smaller than the tolerance) in a segment of the line or polygon.</p></body></html>"))
        self.closeBtn.setText(_translate("SimplifyWindow", "关闭"))
        self.runBtn.setText(_translate("SimplifyWindow", "运行"))
        self.cancelBtn.setText(_translate("SimplifyWindow", "Cancel"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
# import resources_rc
