# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmoothDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmoothDialog(object):
    def setupUi(self, SmoothDialog):
        SmoothDialog.setObjectName("SmoothDialog")
        SmoothDialog.resize(446, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/CartoGrapher/resources/m.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SmoothDialog.setWindowIcon(icon)
        self.closeBtn = QtWidgets.QPushButton(SmoothDialog)
        self.closeBtn.setGeometry(QtCore.QRect(220, 300, 93, 28))
        self.closeBtn.setAutoDefault(False)
        self.closeBtn.setObjectName("closeBtn")
        self.output_checkBox_2 = QtWidgets.QCheckBox(SmoothDialog)
        self.output_checkBox_2.setGeometry(QtCore.QRect(10, 250, 351, 19))
        self.output_checkBox_2.setChecked(True)
        self.output_checkBox_2.setObjectName("output_checkBox_2")
        self.label = QtWidgets.QLabel(SmoothDialog)
        self.label.setGeometry(QtCore.QRect(10, 100, 191, 16))
        self.label.setObjectName("label")
        self.layerCbmBox = QgsMapLayerComboBox(SmoothDialog)
        self.layerCbmBox.setGeometry(QtCore.QRect(10, 50, 160, 27))
        self.layerCbmBox.setObjectName("layerCbmBox")
        self.output_file = QgsFileWidget(SmoothDialog)
        self.output_file.setGeometry(QtCore.QRect(10, 200, 321, 27))
        self.output_file.setObjectName("output_file")
        self.label_5 = QtWidgets.QLabel(SmoothDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_5.setObjectName("label_5")
        self.edit_iteration = QtWidgets.QLineEdit(SmoothDialog)
        self.edit_iteration.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.edit_iteration.setObjectName("edit_iteration")
        self.label_7 = QtWidgets.QLabel(SmoothDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_7.setObjectName("label_7")
        self.runBtn = QtWidgets.QPushButton(SmoothDialog)
        self.runBtn.setGeometry(QtCore.QRect(100, 300, 93, 28))
        self.runBtn.setDefault(True)
        self.runBtn.setObjectName("runBtn")

        self.retranslateUi(SmoothDialog)
        QtCore.QMetaObject.connectSlotsByName(SmoothDialog)

    def retranslateUi(self, SmoothDialog):
        _translate = QtCore.QCoreApplication.translate
        SmoothDialog.setWindowTitle(_translate("SmoothDialog", "Smooth"))
        self.closeBtn.setText(_translate("SmoothDialog", "关闭"))
        self.output_checkBox_2.setText(_translate("SmoothDialog", "Open output file after running algorithm"))
        self.label.setText(_translate("SmoothDialog", "Iteration numbers:"))
        self.label_5.setText(_translate("SmoothDialog", "Input layer or shp："))
        self.label_7.setText(_translate("SmoothDialog", "Smoothed layer："))
        self.runBtn.setText(_translate("SmoothDialog", "运行"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
