# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransformProjDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TransformProjDialog(object):
    def setupUi(self, TransformProjDialog):
        TransformProjDialog.setObjectName("TransformProjDialog")
        TransformProjDialog.resize(400, 354)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/CartoGrapher/resources/m.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TransformProjDialog.setWindowIcon(icon)
        self.Proj_selectBox = QgsProjectionSelectionWidget(TransformProjDialog)
        self.Proj_selectBox.setGeometry(QtCore.QRect(10, 120, 231, 27))
        self.Proj_selectBox.setObjectName("Proj_selectBox")
        self.layerCbmBox = QgsMapLayerComboBox(TransformProjDialog)
        self.layerCbmBox.setGeometry(QtCore.QRect(10, 60, 160, 27))
        self.layerCbmBox.setObjectName("layerCbmBox")
        self.label_5 = QtWidgets.QLabel(TransformProjDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(TransformProjDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_7.setObjectName("label_7")
        self.output_checkBox_2 = QtWidgets.QCheckBox(TransformProjDialog)
        self.output_checkBox_2.setGeometry(QtCore.QRect(10, 240, 351, 19))
        self.output_checkBox_2.setChecked(True)
        self.output_checkBox_2.setObjectName("output_checkBox_2")
        self.output_file = QgsFileWidget(TransformProjDialog)
        self.output_file.setGeometry(QtCore.QRect(10, 200, 321, 27))
        self.output_file.setObjectName("output_file")
        self.closeBtn = QtWidgets.QPushButton(TransformProjDialog)
        self.closeBtn.setGeometry(QtCore.QRect(210, 300, 93, 28))
        self.closeBtn.setObjectName("closeBtn")
        self.runBtn = QtWidgets.QPushButton(TransformProjDialog)
        self.runBtn.setGeometry(QtCore.QRect(90, 300, 93, 28))
        self.runBtn.setObjectName("runBtn")

        self.retranslateUi(TransformProjDialog)
        QtCore.QMetaObject.connectSlotsByName(TransformProjDialog)

    def retranslateUi(self, TransformProjDialog):
        _translate = QtCore.QCoreApplication.translate
        TransformProjDialog.setWindowTitle(_translate("TransformProjDialog", "Transform projection"))
        self.label_5.setText(_translate("TransformProjDialog", "Input layer or shp："))
        self.label_7.setText(_translate("TransformProjDialog", "Projecion transformed："))
        self.output_checkBox_2.setText(_translate("TransformProjDialog", "Open output file after running algorithm"))
        self.closeBtn.setText(_translate("TransformProjDialog", "关闭"))
        self.runBtn.setText(_translate("TransformProjDialog", "运行"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
# import resources_rc
